### ISSUE TITLE
Broken link and typo

### ISSUE THREAD

**Issue by Arthur-Milchior** [awsdocs/amazon-redshift-getting-started-guide#2]
Hi,

On https://docs.aws.amazon.com/redshift/latest/gsg/rs-gsg-connect-to-cluster.html the link to edit the page on github is broken. 

Also, in paragraph 4, you added a space after one varchar and not the other. I don't know which styleguide is used, but it'd be nice to be consistent. I can't do a PR as I don't see the file

**Comment by Arthur-Milchior** [comment]
same 2 problems with https://github.com/awsdocs/amazon-redshift-getting-started-guide/tree/master/doc_source/t_creating_table.md

**Comment by keithhc2** [comment]
@Arthur-Milchior Sorry for the delayed response here. Are you referring to the [Edit this page on GitHub](https://github.com/awsdocs/amazon-redshift-getting-started-guide/blob/master/doc_source/rs-gsg-connect-to-cluster.md) link at the bottom of the page? It seems to work for me. Maybe you can try again? Also, I'm not sure what you're referring to about the space after varchar. We recently updated our docs in the repo, which might have addressed your issues here. I'm closing the issue now, but if the issue still exists, feel free to reopen the issue. Thanks!

**Comment by Arthur-Milchior** [comment]
No issue at all.
To be honest, given that I've since resigned from AWS/Redshift team since I opened this PR, I will not look at it anymore. Just note that I agree with you, link seems to work and the current version of the documentation means the remark about varchar don't makes sens anymore
